name: Debian Build
description: Build for Debian/Ubuntu

inputs:
  arch:
    description: 'aarch64 or amd64'
    required: true
  name:
    description: 'what to name this workflow'
    required: true
  pretty-name:
    description: 'The pretty name to use in the artifact'
    required: true
  cpm-cache-version:
    description: "CPM cache version (e.g. v7)"
    required: true
  devel:
    description: 'development build'
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      uses: ./.github/workflows/setup
      with:
        key: ${{ inputs.name }}-${{ inputs.arch }}
        version: ${{ inputs.cpm-cache-version }}

    - name: Build
      shell: bash
      run: ./.ci/debian/makedeb.sh
      env:
        ARCH: ${{ inputs.arch }}
        DEB_NAME: ${{ inputs.pretty-name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.name }}-${{ inputs.arch }}
        path: ./artifacts/*.deb
        archive: false
