name: " Custom "

on:
  push:
    paths:
      - 'patches/**'
  workflow_dispatch:
    inputs:
      giturl:
        description: 'Specify Clone URL'
        required: true
        default: 'https://github.com/eden-emulator/mirror.git'
      commit:
        description: 'Specify commit (e.g. 3a823de605)'
        required: true
        default: 'default'

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  pushed:
    if: ${{ github.event_name == 'push' }}
    name: Pushed Build
    concurrency:
      group: nightly-build
      cancel-in-progress: false
    uses: ./.github/workflows/buildcustom.yml
    with:
      devel: true
      build-id: 'pushed'
      clone-giturl: 'https://github.com/eden-emulator/mirror.git'
      build-commit: ${{ github.event.head_commit.message }}
    secrets: inherit

  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Manual Build
    concurrency:
      group: nightly-build
      cancel-in-progress: false
    uses: ./.github/workflows/buildcustom.yml
    with:
      devel: true
      build-id: 'manual'
      clone-giturl: ${{ github.event.inputs.giturl }}
      build-commit: ${{ github.event.inputs.commit }}
    secrets: inherit
