name: "[Internal CI] macOS"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  macos:
    name: "macOS (${{ matrix.os.arch }})"
    runs-on: ${{ matrix.os.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: macos-latest
            arch: arm64
        compiler: [universal]

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ runner.os }}-${{ matrix.os.arch }}-${{ matrix.compiler }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Install dependencies
        run: ./.ci/macos/deps.sh

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          version: 6.7.3
          cache: 'true'

      - name: Configure
        run: .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

      - name: Build
        run: cmake --build build

      - name: Package
        run: ./.ci/macos/package.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos
          path: artifacts/*
