name: "[-Manual-] Nightly"

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  BUILD_ID: "manual"

jobs:
  concurrency-check:
    outputs:
      concurrency_group: ${{ steps.concurrency.outputs.group_key }}
      cancel_in_progress: ${{ steps.concurrency.outputs.cancel_in_progress }}
    name: "Concurrency Check"
    runs-on: ubuntu-latest
    steps:
      - name: Define Concurrency group
        id: concurrency
        shell: bash
        run: |
          FORGEJO_BRANCH="${{ github.event.client_payload.branch }}"
          FORGEJO_PR_NUMBER="${{ github.event.client_payload.number }}"
          if [[ -n "${FORGEJO_PR_NUMBER}" ]]; then
            GROUP_KEY="pr-${BUILD_ID}-${FORGEJO_PR_NUMBER}"
            CANCEL_IN_PROGRESS=true
          else
            GROUP_KEY="branch-${BUILD_ID}-${FORGEJO_BRANCH}"
            if [[ "${FORGEJO_BRANCH}" == "master" && "${BUILD_ID}" == "master" ]]; then
              CANCEL_IN_PROGRESS=false
            else
              CANCEL_IN_PROGRESS=true
            fi
          fi
          echo "group_key=$GROUP_KEY" >> "$GITHUB_OUTPUT"
          echo "cancel_in_progress=$CANCEL_IN_PROGRESS" >> "$GITHUB_OUTPUT"
          echo "Concurrency group: $GROUP_KEY, Cancel in progress: $CANCEL_IN_PROGRESS"

  build:
    name: Build
    needs: [concurrency-check]
    concurrency:
      group: ${{ needs.concurrency-check.outputs.concurrency_group }}
      cancel-in-progress: ${{ fromJSON(needs.concurrency-check.outputs.cancel_in_progress) }}
    uses: ./.github/workflows/buildnightly.yml
    with:
      build-id: 'manual'
    secrets: inherit
