name: "[-Manual-] Nightly"

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    concurrency:
      group: manual-build
      cancel-in-progress: false
    uses: ./.github/workflows/buildnightly.yml
    with:
      build-id: 'manual'
    secrets: inherit
