name: "[-Manual-] Nightly"

on:
  workflow_dispatch:

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/buildnightly.yml
    with:
      build-id: 'manual'
    secrets: inherit
