name: "[Internal CI] UNIX"

on:
  workflow_call:
    inputs:
      build-id:
        description: "build id"
        type: string
        required: true
      cpm-cache-version:
        description: "CPM cache version (e.g. v7)"
        type: string
        required: true
      devel:
        description: 'development build'
        type: string
        required: true

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}
  SCCACHE_GHA_ENABLED: "true"
  CCACHE: "true"
  FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
  DEVEL: ${{ inputs.devel }}

jobs:
  unix:
    name: "${{ matrix.os.name }} (${{ matrix.os.arch }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - platform: freebsd
            name: FreeBSD
            arch: amd64
            vm-arch: x86_64
        compiler: [clang]
    env:
      ARCH: ${{ matrix.os.arch }}
      SCCACHE_DIR: ${{ github.workspace }}/.sccache

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Disable man-db updates
        run: sudo rm /var/lib/man-db/auto-update

      - name: Setup
        uses: ./.github/workflows/setup
        with:
          key: ${{ matrix.os.name }}-${{ matrix.os.arch }}-${{ matrix.compiler }}
          version: ${{ inputs.cpm-cache-version }}

      - name: Configure sccache
        uses: actions/github-script@v8.0.0
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('ACTIONS_CACHE_SERVICE_V2', `on`);

      - name: Build (FreeBSD)
        if: matrix.os.platform == 'freebsd'
        uses: vmactions/freebsd-vm@v1.2.4
        with:
          arch: ${{ matrix.os.vm-arch }}
          usesh: true
          envs: 'ARCH DEVEL CCACHE SCCACHE_DIR SCCACHE_GHA_ENABLED ACTIONS_RESULTS_URL ACTIONS_RUNTIME_TOKEN ACTIONS_CACHE_SERVICE_V2'
          prepare: |
            pkg install -y \
              devel/sccache \
              ftp/wget \
              shells/bash
          run: |
            export SCCACHE_PATH=$(which sccache)
            chmod +x ./.ci/freebsd/*

            echo "- Install dependencies"
            bash ./.ci/freebsd/deps.sh

            echo "- Configure"
            bash -ex .ci/common/configure.sh -DCCACHE_PATH=${SCCACHE_PATH}

            echo "- Build"
            cmake --build build

            echo "### SCCache stats" >> "$GITHUB_STEP_SUMMARY"
            echo '```' >> "$GITHUB_STEP_SUMMARY"
            ${SCCACHE_PATH} --show-stats >> "$GITHUB_STEP_SUMMARY" 2>&1
            echo '```' >> "$GITHUB_STEP_SUMMARY"

            echo "- Package"
            bash ./.ci/freebsd/package.sh ${ARCH}

            cmake --install build --prefix install/usr
            cd install
            tar --owner root --group root --zstd -cf Eden-FreeBSD.tar.zst *

      - name: Upload Binary
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ matrix.os.platform }}-binary-${{ matrix.os.arch }}-${{ matrix.compiler }}
          path: install/Eden-${{ matrix.os.name }}.tar.zst
